import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"
import { WagmiProvider, createConfig } from 'wagmi'
import { OnchainKitProvider } from '@coinbase/onchainkit'
import { base } from 'viem/chains'
const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
})
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

const wagmiConfig = createConfig({

})

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<WagmiProvider config={wagmiConfig}>
					<OnchainKitProvider
						apiKey={process.env.PUBLIC_ONCHAINKIT_API_KEY}
						chain={base}
					>
						{children}
					</OnchainKitProvider>
				</WagmiProvider>
			</body>
		</html>
	)
}
